project:
  type: website

website:
  title: "The SDE-Inverse Gaussian Model"
  navbar:
    left:
      - href: index.qmd
        text: Manuscript
      - href: supplementary.qmd
        text: Supplementary
      - href: https://autonomic-navigator.netlify.app/
        text: "Web app"
    right:
      - icon: github
        href: https://github.com/matcasti/2026-XX-SDE-R-R

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true

