project:
  type: website

website:
  title: "The SDE-Inverse Gaussian Model"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/matcasti/2026-XX-SDE-R-R

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

